### ISSUE TITLE
Java11 deprecation warnings

### ISSUE THREAD

**Issue by WolfgangHG** [arquillian/arquillian-extension-warp#218]
There are a few deprecation warnings since the update to Java 11:

```
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/transformation/InstanceCreator.java:[28,33] newInstance() in java.lang.Class has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/server/test/LifecycleTestEnrichmentWatcher.java:[113,27] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/separation/SeparateInvocator.java:[160,34] newInstance() in java.lang.Class has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/utils/Base64.java:[460,27] deprecated item is not annotated with @Deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/server/test/SecurityActions.java:[171,39] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/server/test/SecurityActions.java:[194,40] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/server/test/SecurityActions.java:[282,35] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/verification/SecurityActions.java:[171,39] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/verification/SecurityActions.java:[211,40] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/verification/SecurityActions.java:[268,35] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/execution/SecurityActions.java:[170,39] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/execution/SecurityActions.java:[193,40] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/client/execution/SecurityActions.java:[250,35] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/utils/AnnotationInstanceProvider.java:[70,31] getProxyClass(java.lang.ClassLoader,java.lang.Class<?>...) in java.lang.reflect.Proxy has been deprecated
```

Warning 1: `newInstance() in java.lang.Class has been deprecated`
==>replace by `clazz.getDeclaredConstructor().newInstance()`

Warning 2: `isAccessible() in java.lang.reflect.AccessibleObject has been deprecated`
==>replace by `accessibleObject.canAccess(object)`
(while "object" parameter apparently has to be `null` for static methods).

This causes an animal sniffer error:

```
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0
[ERROR] C:\Temp\github\arquillian-extension-warp\impl\src\main\java\org\jboss\arquillian\warp\impl\utils\AnnotationInvocationHandler.java:266: Undefined reference: boolean java.lang.reflect.Method.canAccess(Object)
```
And this brings us to #199 ....

**Comment by WolfgangHG** [comment]
Warning 3: `getProxyClass(java.lang.ClassLoader,java.lang.Class<?>...) in java.lang.reflect.Proxy has been deprecated`
==>needs further research...

**Comment by WolfgangHG** [comment]
Seems to be more complicated than I thought...

Let's start with one set of warnings: `isAccessible` in the "SecurityActions.java" files (copied to four places):

`AccessibleObject.isAccessible` (https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/reflect/AccessibleObject.html#isAccessible()) just returns the boolean "override" that is set by `setAccessible(boolean)`. So it is just a check whether the security override was called before. It is no check whether the field is private or not.
The method `canAccess` that should be used according to the JavaDoc is more complicated: for non static fields, you have to specifiy an instance.
Attached is a small sample that does this checking ("Main.java" and "TestClass.java") and proves that `isAccessible` is `false` for all fields, while `canAccess` would return `true` for public/protected fields and `false` for private fields.
[ReflectionTest.zip](https://github.com/user-attachments/files/17606567/ReflectionTest.zip)

I thought I had resolved this, see attached diff. I implemented it only for "impl/src/main/java/org/jboss/arquillian/warp/impl/server/test/SecurityActions.java", method "getFields".
[accessible.patch](https://github.com/user-attachments/files/17606582/accessible.patch)

But now, an exception occurs:

```
Caused by: java.lang.NoClassDefFoundError: Unable to load nest-host class (org/jboss/arquillian/warp/ftest/BasicWarpTest) of org.jboss.arquillian.warp.ftest.BasicWarpTest$1
        at java.base/jdk.internal.reflect.Reflection.areNestMates(Native Method)
        at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:150)
        at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:633)
        at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:626)
        at java.base/java.lang.reflect.AccessibleObject.canAccess(AccessibleObject.java:479)
        at deployment.test.war//org.jboss.arquillian.warp.impl.server.test.SecurityActions.canAccess(SecurityActions.java:316)
        at deployment.test.war//org.jboss.arquillian.warp.impl.server.test.SecurityActions$4.run(SecurityActions.java:285)
        at deployment.test.war//org.jboss.arquillian.warp.impl.server.test.SecurityActions$4.run(SecurityActions.java:278)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
        at deployment.test.war//org.jboss.arquillian.warp.impl.server.test.SecurityActions.getFields(SecurityActions.java:278)
        at deployment.test.war//org.jboss.arquillian.warp.impl.server.test.LifecycleTestEnrichmentWatcher.backupAllFields(LifecycleTestEnrichmentWatcher.java:68)
        at deployment.test.war//org.jboss.arquillian.warp.impl.server.test.LifecycleTestEnrichmentWatcher.rememberFieldValues(LifecycleTestEnrichmentWatcher.java:49)
```

Reason seems to be: "BasicWarpTest" has some anonymous classes (e.g. "Inspection"). Probably Warp sends only those internal classes to the server, but not the outer class.

To reproduce it (after applying the patch):
`mvnw clean install -Pwildfly-remote -Dtest="org.jboss.arquillian.warp.ftest.BasicWarpTest.java" -Dsurefire.failIfNoSpecifiedTests=false`


Suggestion: remove all `isAccessible` checks. Don't add `canAccess` calls instead. Just do `setAccessible(true)` for all fields/methods, without any further check. This does not seem to have any side effects besides the fact, that the internal flag "override" is set at every call to `setAccessible`

@rhusar What do you think?

**Comment by WolfgangHG** [comment]
Warning 4 (since JakartaEE10):

```
"The constructor FacesContextFactory() is deprecated" in /arquillian-warp-jsf/src/main/java/org/jboss/arquillian/warp/jsf/FacesContextFactory.java
"The constructor FacesContextWrapper() is deprecated" in /arquillian-warp-jsf/src/main/java/org/jboss/arquillian/warp/jsf/FacesContextFactory.java
```

**Comment by WolfgangHG** [comment]
A maven build reports two more warnings that are not shown in Eclipse:

```
[WARNING] .../arquillian-extension-warp/impl/src/main/java/org/jboss/arquillian/warp/impl/utils/Base64.java:[460,27] deprecated item is not annotated with @Deprecated
...
[WARNING] /.../arquillian-extension-warp/impl/src/test/java/org/jboss/arquillian/warp/impl/client/execution/TestRequestExecutionSynchronization.java:[120,17] finalize() in java.lang.Object has been deprecated

```

**Comment by rhusar** [comment]
Sounds like this is done, thanks @WolfgangHG !
